import { PrismaClient } from "@prisma/client";
import { sectionsToTipTap } from "./tiptap";

const BLOG_SEED = [
    {
        slug:        "answer-engine-optimization-2026",
        category:    "Professional Services",
        title:       "How Answer Engine Optimization Changes Search in 2026",
        excerpt:     "Explore how AEO is reshaping the way brands get discovered in AI-powered search experiences.",
        author:      "Simran Shrestha",
        readTime:    "8 min read",
        coverImage:  "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
        tags:        ["DevOps", "Computing"],
        published:   true,
        publishedAt: new Date("2025-06-19"),
        content: sectionsToTipTap([
            { type: "heading",    text: "Overview" },
            { type: "paragraph",  text: "AppArmor (Application Armor) is a Linux security module (LSM) that provides mandatory access control (MAC) for programs. MAC is a security model where access to resources (files, directories, network sockets, etc.) is strictly controlled by a central policy. It restricts programs' capabilities with per-application profiles, helping to confine them and limit the damage that could be done by vulnerabilities or misconfigurations." },
            { type: "heading",    text: "Key Concepts of AppArmor" },
            { type: "bullets",    items: ["Profiles: Each application or process has a profile that defines what files and capabilities it can access.", "Work with NLP technologies and fine-tune Large Language Models (LLMs)", "Use agentic frameworks like crewAI, LangGraph, or similar orchestration tools", "Build scalable APIs using REST and GraphQL", "Deploy solutions on cloud platforms (AWS, GCP, Azure, etc.)", "Program in Python, Node.js, or similar modern languages", "Utilize tools like TensorFlow, PyTorch, Hugging Face, LangChain", "Preprocess, clean, and evaluate ML data/models", "Follow best practices: Git, testing, CI/CD, and documentation"] },
            { type: "heading",    text: "How AppArmor Works" },
            { type: "bullets",    items: ["Profiles: Each application or process has a profile that defines what files and capabilities it can access.", "Work with NLP technologies and fine-tune Large Language Models (LLMs)", "Use agentic frameworks like crewAI, LangGraph, or similar orchestration tools", "Build scalable APIs using REST and GraphQL", "Deploy solutions on cloud platforms (AWS, GCP, Azure, etc.)", "Program in Python, Node.js, or similar modern languages", "Utilize tools like TensorFlow, PyTorch, Hugging Face, LangChain", "Preprocess, clean, and evaluate ML data/models", "Follow best practices: Git, testing, CI/CD, and documentation"] },
            { type: "heading",    text: "Common Commands" },
            { type: "bullets",    items: ["Profiles: Each application or process has a profile that defines what files and capabilities it can access.", "Work with NLP technologies and fine-tune Large Language Models (LLMs)", "Use agentic frameworks like crewAI, LangGraph, or similar orchestration tools", "Build scalable APIs using REST and GraphQL"] },
            { type: "heading",    text: "User Cases" },
            { type: "paragraph",  text: "AppArmor is particularly useful for hardening Linux systems by restricting what applications can do, based on defined security policies." },
            { type: "subheading", text: "1. Hardening Network-Exposed Services" },
            { type: "bullets",    items: ["Use Case: Confining web servers, databases, or mail servers to reduce risk from vulnerabilities.", "Examples: MySQL: Restrict it to its own data directory.", "Postfix/Dovecot: Limit filesystem access to mail directories only.", "Apache/Nginx: Prevent from accessing /home, mounting devices, or executing libraries outside /usr/lib."] },
            { type: "subheading", text: "2. Hardening Network-Exposed Services" },
            { type: "bullets",    items: ["Use Case: Confining web servers, databases, or mail servers to reduce risk from vulnerabilities.", "Examples: MySQL: Restrict it to its own data directory.", "Postfix/Dovecot: Limit filesystem access to mail directories only.", "Apache/Nginx: Prevent from accessing /home, mounting devices, or executing libraries outside /usr/lib."] },
            { type: "code",       language: "bash", text: "sudo apt install apparmor apparmor-utils\nsudo systemctl enable apparmor\nsudo systemctl start apparmor" },
            { type: "paragraph",  text: "AppArmor is usually pre-installed on Ubuntu and Debian. If not installed, you can install it with:" },
            { type: "code",       language: "bash", text: "sudo apt install apparmor apparmor-utils\nsudo systemctl enable apparmor\nsudo systemctl start apparmor" },
            { type: "paragraph",  text: "AppArmor is a powerful and easy-to-use Linux security tool that helps you control what applications and scripts can do on your system. Whether you're protecting sensitive files, restricting untrusted scripts, or securing containers, AppArmor acts like a set of guardrails that enforce the principle of \"least privilege\"." },
        ]),
    },
    {
        slug:        "geo-brand-visibility-ai",
        category:    "Professional Services",
        title:       "How Answer Engine Optimization Changes Search in 2026",
        excerpt:     "Explore how AEO is reshaping the way brands get discovered in AI-powered search experiences.",
        author:      "Simran Shrestha",
        readTime:    "6 min read",
        coverImage:  "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        tags:        ["GEO", "AI Visibility"],
        published:   true,
        publishedAt: new Date("2025-05-22"),
        content: sectionsToTipTap([
            { type: "heading",   text: "Overview" },
            { type: "paragraph", text: "Generative Engine Optimization (GEO) is the next evolution of SEO, focusing on how brands appear in AI-generated responses rather than traditional search results." },
            { type: "heading",   text: "Key Strategies" },
            { type: "bullets",   items: ["Build authoritative content clusters", "Use structured data and schema markup", "Optimize for conversational queries", "Establish entity associations across the web"] },
        ]),
    },
    {
        slug:        "entity-optimisation-ai-models",
        category:    "Professional Services",
        title:       "How Answer Engine Optimization Changes Search in 2026",
        excerpt:     "Explore how AEO is reshaping the way brands get discovered in AI-powered search experiences.",
        author:      "Simran Shrestha",
        readTime:    "5 min read",
        coverImage:  "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
        tags:        ["Entity SEO", "AI Models"],
        published:   true,
        publishedAt: new Date("2025-05-22"),
        content: sectionsToTipTap([
            { type: "heading",   text: "Overview" },
            { type: "paragraph", text: "Entity optimization helps AI models reliably identify, understand, and recommend your brand. This guide covers the core techniques." },
            { type: "heading",   text: "Core Concepts" },
            { type: "bullets",   items: ["Knowledge graph integration", "Schema.org markup for entities", "Consistent NAP (Name, Address, Phone)", "Cross-platform brand mentions"] },
        ]),
    },
    {
        slug:        "chatgpt-brand-citation-strategy",
        category:    "AI Strategy",
        title:       "Getting Your Brand Cited by ChatGPT and Perplexity",
        excerpt:     "A practical guide to crafting content that AI assistants actively reference and recommend.",
        author:      "Simran Shrestha",
        readTime:    "7 min read",
        coverImage:  "https://images.unsplash.com/photo-1686191128892-3b37add4c844?w=800&q=80",
        tags:        ["ChatGPT", "Content Strategy"],
        published:   true,
        publishedAt: new Date("2025-04-15"),
        content: sectionsToTipTap([
            { type: "heading",   text: "Overview" },
            { type: "paragraph", text: "AI language models cite sources based on authority, relevance, and structured clarity. This post breaks down the exact content patterns that trigger brand citations." },
            { type: "heading",   text: "Citation Triggers" },
            { type: "bullets",   items: ["Clear factual statements with citations", "FAQ-formatted content", "Authoritative backlink profiles", "Consistent brand mentions across domains"] },
        ]),
    },
    {
        slug:        "aeo-vs-seo-differences",
        category:    "B2B SaaS",
        title:       "AEO vs SEO: What Every B2B Brand Must Know in 2026",
        excerpt:     "Traditional SEO is no longer enough. Here's how Answer Engine Optimization differs and why you need both.",
        author:      "Simran Shrestha",
        readTime:    "9 min read",
        coverImage:  "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
        tags:        ["SEO", "AEO", "B2B"],
        published:   true,
        publishedAt: new Date("2025-03-10"),
        content: sectionsToTipTap([
            { type: "heading",   text: "Overview" },
            { type: "paragraph", text: "Search engine optimization focuses on ranking in Google. Answer engine optimization focuses on being the recommended answer in AI systems. They require different strategies." },
            { type: "heading",   text: "Key Differences" },
            { type: "bullets",   items: ["SEO targets keywords; AEO targets intents", "SEO measures rankings; AEO measures citations", "SEO uses backlinks; AEO uses entity authority", "Both require high-quality content"] },
        ]),
    },
    {
        slug:        "ai-visibility-for-ecommerce",
        category:    "E-commerce",
        title:       "AI Visibility Strategies for E-commerce Brands in 2026",
        excerpt:     "How product-based brands can dominate AI recommendation engines and drive qualified traffic.",
        author:      "Simran Shrestha",
        readTime:    "6 min read",
        coverImage:  "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
        tags:        ["E-commerce", "AI Ranking"],
        published:   true,
        publishedAt: new Date("2025-02-28"),
        content: sectionsToTipTap([
            { type: "heading",   text: "Overview" },
            { type: "paragraph", text: "E-commerce brands face unique challenges in AI search. Product discovery is increasingly happening through conversational AI rather than traditional search." },
            { type: "heading",   text: "Strategies" },
            { type: "bullets",   items: ["Optimize product descriptions for natural language", "Build review authority across platforms", "Use structured product schema", "Target long-tail conversational queries"] },
        ]),
    },
];

export async function seedBlog(prisma: PrismaClient): Promise<void> {
    for (const post of BLOG_SEED) {
        const data = {
            ...post,
            tags: JSON.stringify(post.tags),
            content: JSON.stringify(post.content),
        };
        await prisma.blogPost.upsert({ where: { slug: post.slug }, update: data as any, create: data as any });
    }
    console.log(`  ✓ ${BLOG_SEED.length} blog posts seeded`);
}
